sudo: required
services:
  - docker
  
before_install:
  - docker build -t sl10/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true -t sl10/react-test npm test

after_success:
  - docker build -t sl10/multi_container_client ./client
  - docker build -t sl10/multi_container_nginx ./nginx
  - docker build -t sl10/multi_container_server ./server
  - docker build -t sl10/multi_container_worker ./worker
  # log into docker cli /w one command by using encrypted environment variables in travis CI
  - echo "$docker_password" | docker login -u "$docker_id" --password-stdin
  # push images to docker hub
  - docker push sl10/multi_container_client
  - docker push sl10/multi_container_nginx
  - docker push sl10/multi_container_server
  - docker push sl10/multi_container_worker
  
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker 
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-012136132533
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY